name: Build ADFS Adapter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Removed the Setup .NET step since .NET Framework 4.8 is pre-installed on Windows runners

      - name: Restore packages
        run: msbuild AdfsToKeycloakAdapter.sln /t:Restore

      - name: Build project
        run: msbuild AdfsToKeycloakAdapter.sln /p:Configuration=Release

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: AdfsToKeycloakAdapter
          path: |
            src/AdfsToKeycloakAdapter/bin/Release/*.dll

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: AdfsToKeycloakAdapter

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          files: |
            *.dll